services:
  bot:
    build: .
    container_name: aiogram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./bot.db:/app/bot.db
    environment:
      - PYTHONUNBUFFERED=1
